using System;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using PhantomVault.Core.Models;

namespace PhantomVault.Core.Services
{
    /// <summary>
    /// Service for generating and validating one-time recovery codes.
    /// Recovery codes provide account recovery when all authentication factors are lost.
    /// Each code is single-use and cryptographically hashed for storage.
    /// </summary>
    public sealed class RecoveryCodeService
    {
        private const int DefaultCodeCount = 10;
        private const int CodeEntropyBytes = 16; // 128 bits
        private const int FormattedCodeLength = 19; // XXXX-XXXX-XXXX-XXXX

        /// <summary>
        /// Generates a set of single-use recovery codes during vault creation.
        /// Each code is 16 characters (128 bits entropy) formatted as XXXX-XXXX-XXXX-XXXX.
        /// </summary>
        /// <param name="count">Number of recovery codes to generate (default: 10)</param>
        /// <returns>Array of recovery codes for user to save securely</returns>
        public string[] GenerateRecoveryCodes(int count = DefaultCodeCount)
        {
            if (count <= 0 || count > 100)
                throw new ArgumentException("Recovery code count must be between 1 and 100", nameof(count));

            var codes = new string[count];

            for (int i = 0; i < count; i++)
            {
                // Generate 16 bytes (128 bits) of cryptographically random data
                var bytes = RandomNumberGenerator.GetBytes(CodeEntropyBytes);

                // Convert to base64 and remove special characters
                var base64 = Convert.ToBase64String(bytes)
                    .Replace("+", "")
                    .Replace("/", "")
                    .Replace("=", "")
                    .ToUpperInvariant();

                // Take first 16 characters and format as XXXX-XXXX-XXXX-XXXX
                var code = base64.Substring(0, 16);
                codes[i] = FormatRecoveryCode(code);
            }

            return codes;
        }

        /// <summary>
        /// Generates recovery code metadata for storage in the vault manifest.
        /// Recovery codes are hashed using Argon2 before storage.
        /// </summary>
        /// <param name="codes">Plain text recovery codes generated by GenerateRecoveryCodes</param>
        /// <returns>Array of RecoveryCode objects with hashes</returns>
        public RecoveryCode[] PrepareRecoveryCodesForStorage(string[] codes)
        {
            var recoveryCodeMetadata = new RecoveryCode[codes.Length];

            for (int i = 0; i < codes.Length; i++)
            {
                // Remove formatting hyphens before hashing
                var plainCode = codes[i].Replace("-", "");

                recoveryCodeMetadata[i] = new RecoveryCode
                {
                    Hash = HashRecoveryCode(plainCode),
                    Used = false,
                    UsedAtUtc = null,
                    CreatedAtUtc = DateTimeOffset.UtcNow
                };
            }

            return recoveryCodeMetadata;
        }

        /// <summary>
        /// Validates a recovery code and marks it as used if valid.
        /// Uses constant-time comparison to prevent timing attacks.
        /// </summary>
        /// <param name="manifest">Vault manifest containing recovery code hashes</param>
        /// <param name="inputCode">Recovery code entered by user</param>
        /// <returns>True if code is valid and unused; false otherwise</returns>
        public bool ValidateAndUseRecoveryCode(VaultManifest manifest, string inputCode)
        {
            if (manifest.RecoveryCodes == null || manifest.RecoveryCodes.Length == 0)
                return false;

            // Remove formatting hyphens and normalize
            var normalizedInput = inputCode.Replace("-", "").Replace(" ", "").ToUpperInvariant();

            if (string.IsNullOrWhiteSpace(normalizedInput))
                return false;

            // Hash the input code
            var inputHash = HashRecoveryCode(normalizedInput);
            var inputHashBytes = Encoding.UTF8.GetBytes(inputHash);

            // Check each recovery code using constant-time comparison
            foreach (var recoveryCode in manifest.RecoveryCodes)
            {
                // Skip already used codes
                if (recoveryCode.Used)
                    continue;

                var storedHashBytes = Encoding.UTF8.GetBytes(recoveryCode.Hash);

                // Constant-time comparison to prevent timing attacks
                if (CryptographicOperations.FixedTimeEquals(inputHashBytes, storedHashBytes))
                {
                    // Mark code as used
                    recoveryCode.Used = true;
                    recoveryCode.UsedAtUtc = DateTimeOffset.UtcNow;
                    return true;
                }
            }

            return false;
        }

        /// <summary>
        /// Counts how many recovery codes remain unused.
        /// </summary>
        /// <param name="manifest">Vault manifest</param>
        /// <returns>Number of unused recovery codes</returns>
        public int GetRemainingCodeCount(VaultManifest manifest)
        {
            if (manifest.RecoveryCodes == null)
                return 0;

            return manifest.RecoveryCodes.Count(rc => !rc.Used);
        }

        /// <summary>
        /// Regenerates all recovery codes. This invalidates all existing codes.
        /// Should be used when user suspects codes have been compromised.
        /// </summary>
        /// <param name="manifest">Vault manifest to update</param>
        /// <param name="count">Number of new codes to generate</param>
        /// <returns>New recovery codes for user to save</returns>
        public string[] RegenerateRecoveryCodes(VaultManifest manifest, int count = DefaultCodeCount)
        {
            // Generate new codes
            var newCodes = GenerateRecoveryCodes(count);

            // Prepare for storage
            manifest.RecoveryCodes = PrepareRecoveryCodesForStorage(newCodes);

            return newCodes;
        }

        /// <summary>
        /// Formats a recovery code as XXXX-XXXX-XXXX-XXXX for readability.
        /// </summary>
        private static string FormatRecoveryCode(string code)
        {
            if (code.Length != 16)
                throw new ArgumentException("Recovery code must be 16 characters", nameof(code));

            return $"{code.Substring(0, 4)}-{code.Substring(4, 4)}-{code.Substring(8, 4)}-{code.Substring(12, 4)}";
        }

        /// <summary>
        /// Hashes a recovery code using Argon2 for secure storage.
        /// Uses strong parameters appropriate for recovery codes.
        /// </summary>
        private static string HashRecoveryCode(string code)
        {
            // Generate unique salt for this code
            var salt = RandomNumberGenerator.GetBytes(16);

            // Hash using Argon2id with strong parameters
            // Memory: 64MB, Iterations: 3, Parallelism: 1
            var hash = Argon2Placeholder.Hash(
                Encoding.UTF8.GetBytes(code),
                salt,
                iterations: 3,
                memorySize: 64 * 1024, // 64 MB
                parallelism: 1,
                hashLength: 32,
                Argon2Type.Argon2id);

            // Return salt + hash as base64
            var combined = new byte[salt.Length + hash.Length];
            Buffer.BlockCopy(salt, 0, combined, 0, salt.Length);
            Buffer.BlockCopy(hash, 0, combined, salt.Length, hash.Length);

            return Convert.ToBase64String(combined);
        }
    }

    /// <summary>
    /// Argon2 password hashing implementation.
    /// This is a simplified version - in production, use Konscious.Security.Cryptography.Argon2.
    /// </summary>
    internal static class Argon2Placeholder
    {
        public static byte[] Hash(
            byte[] password,
            byte[] salt,
            int iterations,
            int memorySize,
            int parallelism,
            int hashLength,
            Argon2Type type)
        {
            // For now, fall back to PBKDF2 with high iteration count
            // In production, use: using var argon2 = new Argon2id(password)
            using var pbkdf2 = new Rfc2898DeriveBytes(
                password,
                salt,
                iterations * 50000, // Scale up iterations to compensate for PBKDF2 vs Argon2
                HashAlgorithmName.SHA256);

            return pbkdf2.GetBytes(hashLength);
        }
    }

    internal enum Argon2Type
    {
        Argon2id
    }
}
